# Generated by Django 4.0.5 on 2022-06-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_datetime']},
        ),
    ]
